name: Deploy Prod

on:
  push:
    branches: [main]

concurrency:
  group: deploy-prod
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      stage: prod
    secrets: inherit
